---

- name: dpkg configure
  command: dpkg --configure -a
  changed_when: false

- name: install system packages and utils
  apt:
    pkg: ['ntp', 'openssl', 'git', 'telnet', 'figlet', 'git-core', 'htop', 'wget', 'python-pip',
   'zip', 'vim', 'vim-common', 'curl', 'rsyslog', 'libjson-xs-perl']
    state: "{{ state }}"
    update_cache: true
    cache_valid_time: 5400
  changed_when: false
