---
- import_tasks: users.yml
- import_tasks: install.yml
- import_tasks: aws.yml
  when: aws
- import_tasks: zsh.yml
  vars:
    user: ubuntu

- import_tasks: zsh.yml
  vars:
    user: root
    home_dir: '/'
