---

- import_tasks: install-apt-pkg.yml
  when: ansible_facts['distribution'] == "Ubuntu"

- import_tasks: install-yum-pkg.yml
  when: (ansible_facts['distribution'] == "CentOS" or (ansible_facts['distribution'] == "Amazon")

- import_tasks: zsh.yml
  vars:
    user: ubuntu

- import_tasks: zsh.yml
  vars:
    user: root
    home_dir: "/"
