---
## Install Oh-my-zsh

- name: install git and zsh debian
  apt:
    name: ['git', 'zsh']
    state: present
    update_cache: true
    cache_valid_time: 5400
  when: ansible_facts['distribution'] == "Ubuntu"

- name: install git zsh cento or amazon
  yum:
    name: zsh
    state: present
    update_cache: true
  when: (ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version']
          == "7") or (ansible_facts['distribution'] == "Amazon")

- name: clone oh-my-zsh repo
  git:
    depth: 1
    repo: "{{ item.name }}"
    version: master
    dest: /usr/local/share/{{ item.dir }}
  with_items:
    - name: https://github.com/robbyrussell/oh-my-zsh
      dir: oh-my-zsh
    - name: https://github.com/zsh-users/zsh-syntax-highlighting
      dir: zsh-syntax-highlighting
    - name: git://github.com/zsh-users/zsh-autosuggestions
      dir: zsh-autosuggestions

- name: create conf folder in home directory
  file:
    path: "{{ item }}"
    state: directory
    mode: 0777
  with_items:
    - "/usr/local/share/oh-my-zsh/conf/"
    - "/usr/local/share/oh-my-zsh/cache/"

- name: deploy .zshrc
  template:
    src: config/zshrc.in
    dest: /usr/local/share/oh-my-zsh/conf/zshrc
    mode: 0777

- name: deploy .extra on centos
  template:
    src: config/extra.in
    dest: "/home/{{ centos_user }}/.extra"
    mode: 0777
  when: (ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "7")

- name: deploy .bash_profile on centos
  template:
    src: config/bash_profile.in
    dest: "/home/{{ centos_user }}/.bash_profile"
    mode: 0777
  when: (ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "7")

- name: remove standard zshrc on centos
  file:
    path: "/home/{{ centos_user }}/.zshrc"
    state: absent
  changed_when: false
  when: (ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "7")

- name: symlink zshrc on centos
  file:
    path: "/home/{{ centos_user }}/.zshrc"
    src: /usr/local/share/oh-my-zsh/conf/zshrc
    state: link
    mode: 0777
  changed_when: false
  when: (ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "7")

- name: set zsh as default shell on centos
  shell: "chsh -s $(which zsh) {{ centos_user }}"
  changed_when: false
  when: (ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "7")

- name: deploy .extra on amazonlinux
  template:
    src: config/extra.in
    dest: "/home/{{ amazon_user }}/.extra"
    mode: 0777
  when: (ansible_facts['distribution'] == "Amazon")

- name: deploy .bash_profile on amazonlinux
  template:
    src: config/bash_profile.in
    dest: "/home/{{ amazon_user }}/.bash_profile"
    mode: 0777
  when: (ansible_facts['distribution'] == "Amazon")

- name: remove standard zshrc on amazonlinux
  file:
    path: "/home/{{ amazon_user }}/.zshrc"
    state: absent
  changed_when: false
  when: (ansible_facts['distribution'] == "Amazon")

- name: symlink zshrc on amazonlinux
  file:
    path: "/home/{{ amazon_user }}/.zshrc"
    src: /usr/local/share/oh-my-zsh/conf/zshrc
    state: link
    mode: 0777
  changed_when: false
  when: (ansible_facts['distribution'] == "Amazon")

- name: set zsh as default shell on amazonlinux
  shell: "chsh -s $(which zsh) {{ amazon_user }}"
  changed_when: false
  when: (ansible_facts['distribution'] == "Amazon")


- name: deploy .extra
  template:
    src: config/extra.in
    dest: "{{ home_dir | default('/home/') }}{{ user }}/.extra"
    mode: 0777
  when: ansible_facts['distribution'] == "Ubuntu"

- name: deploy .bash_profile
  template:
    src: config/bash_profile.in
    dest: "{{ home_dir | default('/home/') }}{{ user }}/.bash_profile"
    mode: 0777
  when: ansible_facts['distribution'] == "Ubuntu"

- name: remove standard zshrc
  file:
    path: "{{ home_dir | default('/home/') }}{{ user }}/.zshrc"
    # path: "/home/{{ user }}/.zshrc"
    state: absent
  changed_when: false
  when: ansible_facts['distribution'] == "Ubuntu"

- name: symlink zshrc
  file:
    path: "{{ home_dir | default('/home/') }}{{ user }}/.zshrc"
    src: /usr/local/share/oh-my-zsh/conf/zshrc
    state: link
    mode: 0777
  changed_when: false
  when: ansible_facts['distribution'] == "Ubuntu"

- name: set zsh as default shell
  shell: "chsh -s $(which zsh) {{ user }}"
  changed_when: false
  when: ansible_facts['distribution'] == "Ubuntu"
